### ISSUE TITLE
对vue的版本有要求吗?

### ISSUE THREAD

**Issue by xujz520** [wechat-miniprogram/kbone-template-vue#11]
当前 `kbone-template-vue` 使用的是 `"vue": "^2.5.2" `
但是我想用 `vue: 2.6.0` 的插槽新语法.
然后我就直接将vue升级到了 `"vue": "^2.6.11"` 在 `npm run mp` 的时候报错:
```
    at tokenize (D:\kbone-template-test\node_modules\vue-improve-loader\src\parser.js:100:37)
    at Object.parse (D:\kbone-template-test\node_modules\vue-improve-loader\src\parser.js:175:5)
    at Object.module.exports (D:\kbone-template-test\node_modules\vue-improve-loader\src\index.js:39:16)
    at LOADER_EXECUTION (D:\kbone-template-test\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (D:\kbone-template-test\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (D:\kbone-template-test\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at D:\kbone-template-test\node_modules\loader-runner\lib\LoaderRunner.js:205:4
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
17% building 48/68 modules 20 active ....js??
vue-loader-options!D:\kbone-template-test\node_modules\vue-improve-loader\src\index.js!D:\kbone-template-test\src\pages\live\index\App.vue?
vue&type=style&index=0&lang=less&
Error: parse error: <template #button>
```

**Comment by JuneAndGreen** [comment]
这个看来是 vue-improve-loader 的报错，这个依赖是什么版本呢？另外你用的新语法的那个模板也给下？

**Comment by xujz520** [comment]
我仅仅将vue的版本升级了一下:
```json
"dependencies": {
    "kbone-api": "^0.2.1",
    "kbone-ui": "^0.6.5",
    "vant": "^2.8.4",
    // "vue": "^2.5.2",
    "vue": "^2.6.11",
  }
```

```html
<van-field
  v-model="sms"
  center
  clearable
  label="短信验证码"
  placeholder="请输入短信验证码"
>
  <template #button>
    <van-button size="small" type="primary">发送验证码</van-button>
  </template>
</van-field>
```

**Comment by xujz520** [comment]
`"vue-improve-loader": "^0.3.5"` 这样就好了

**Comment by JuneAndGreen** [comment]
已更新：https://github.com/wechat-miniprogram/kbone-template-vue/commit/3ddf6c92882692c914cbcb8ed5fc0e86752e96fe
